apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: YOUR-USERNAME
spec:
  name: YOUR-USERNAME
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: quay.io/supathak/github-ttm-test:v3
          name: github-pr-ttm-custom-classifier
          imagePullPolicy: Always
          env:
          - name: GUNICORN_WORKERS
            value: '1'
          - name: GUNICORN_THREADS
            value: '2'
          - name: S3_ENDPOINT
            valueFrom:
              secretKeyRef:
                key: AIOPS_TOOLS_WORKSHOP_S3_ENDPOINT
                name: s3buckets
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: AIOPS_TOOLS_WORKSHOP_AWS_ACCESS_KEY_ID
                name: s3buckets
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: AIOPS_TOOLS_WORKSHOP_AWS_SECRET_ACCESS_KEY
                name: s3buckets
          - name: S3_BUCKET
            valueFrom:
              secretKeyRef:
                key: AIOPS_TOOLS_WORKSHOP_BUCKET
                name: s3buckets
          - name: {CEPH_BUCKET_PREFIX}/{ORG}/{REPO}/ttm-model
    graph:
      children: []
      endpoint:
        type: REST
      name: github-pr-ttm-custom-classifier
      type: MODEL
    name: github-pr-ttm-custom-predictor
    replicas: 1
